version: "3.9"

name: "Back-end Database and Front-end Web Server Setup"
description: "This Docker Compose file sets up a PostgreSQL database, a Node.js application, and an Nginx web server. The PostgreSQL database is used to store data for the Node.js application, and Nginx serves static files and acts as a reverse proxy for the Node.js application."

services:
  web:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: sampledb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app_network

  app:
    build: .
    container_name: node_server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app_network
    depends_on:
      - db

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
